version: '3'
services:

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/notebook
    ports:
      - "3000:3000"

  redis:
    image: redis:3.2-alpine
    command: redis-server --port 7479
    ports:
      - "7479:7479"

  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      - redis