# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7e8458bf3a8fef139efbfdd69c134efc1fede299c480209eee2919c85ef949f2b5cdf5c21a692d2f88286cb6498a858f9d6ff867d0c23e0570e07a30f71d462

test:
  secret_key_base: b7b1dee85cc799fbca33e640f96c0c5edde276e380878e6095165c82e344843f1f102356c1ff5e8507ec5c398a69b590bf4564a287c381d3c7cabd7a7f3788a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
